PLUGIN = PLUGIN or {}

PLUGIN.name = "Ranking System"
PLUGIN.author = "Generated by Claude"
PLUGIN.description = "Adds a basic ranking system to the server."

-- Shared rank table (identical for both factions during testing)
local sharedRanks = {
    { fullRank = "Private",             rank = "Pvt"  },
    { fullRank = "Private First Class", rank = "Pfc"  },
    { fullRank = "Lance Corporal",      rank = "Lcpl" },
    { fullRank = "Corporal",            rank = "Cpl"  },
    { fullRank = "Sergeant",            rank = "Sgt"  },
    { fullRank = "Lieutenant",          rank = "Lt"   },
    { fullRank = "Captain",             rank = "Cpt"  }
}

local rankTable = {
    GERMAN  = sharedRanks,
    BRITISH = sharedRanks
}

-- Faction mapping
local factionDivisionMap = {
    [FACTION_GERMAN]  = "GERMAN",
    [FACTION_BRITISH] = "BRITISH"
}

-- Helper: strip a rank prefix from a name only if it matches a known rank.
-- Prevents accidentally chopping the first word off a normal name.
local function StripRankPrefix(name)
    for _, rankData in ipairs(sharedRanks) do
        local prefix = rankData.rank .. " "
        if name:sub(1, #prefix) == prefix then
            return name:sub(#prefix + 1)
        end
    end
    return name
end

local function GetRankIndex(division, rankShort)
    for index, rank in ipairs(rankTable[division]) do
        if rank.rank == rankShort then
            return index
        end
    end
    return nil
end

-- PLUGIN Functions
function PLUGIN:OnCharacterCreated(client, character)
    local faction = character:GetFaction()
    if factionDivisionMap[faction] then
        self:SetupRank(client, character)
    end
end

function PLUGIN:PlayerLoadedCharacter(client, character, lastChar)
    local faction = character:GetFaction()
    if not factionDivisionMap[faction] then return end

    if not character:GetData("rankinfo") then
        self:SetupRank(client, character)
    end
end

function PLUGIN:SetupRank(client, character)
    local faction = character:GetFaction()
    if not factionDivisionMap[faction] then return end

    local division = factionDivisionMap[faction]
    if not division then return end

    local name = StripRankPrefix(character:GetName())
    character:SetName("Pvt " .. name)

    character:SetData("rankinfo", {
        paygrade = 1,
        division = division,
        fullRank = "Private",
        rank     = "Pvt"
    })
end

-- Promotion permission: admin only.
function PLUGIN:CanPromoteTarget(promoter, target)
    if not factionDivisionMap[target:GetFaction()] then return false end
    if promoter:GetPlayer():IsAdmin() then return true end
    return false
end

function PLUGIN:Promote(character, promoter)
    if not factionDivisionMap[character:GetFaction()] then return false end
    if not promoter then return false end

    if not self:CanPromoteTarget(promoter, character) then
        promoter:GetPlayer():Notify("You don't have permission to promote this person.")
        return false
    end

    local rankinfo    = character:GetData("rankinfo")
    local newpaygrade = rankinfo.paygrade + 1

    if newpaygrade > #rankTable[rankinfo.division] then
        promoter:GetPlayer():Notify("This character is already at the highest rank.")
        return false
    end

    local newrank     = rankTable[rankinfo.division][newpaygrade].rank
    local newfullRank = rankTable[rankinfo.division][newpaygrade].fullRank

    character:SetName(newrank .. " " .. StripRankPrefix(character:GetName()))

    character:SetData("rankinfo", {
        paygrade = newpaygrade,
        division = rankinfo.division,
        fullRank = newfullRank,
        rank     = newrank
    })

    character:GetPlayer():Notify("Congratulations, you have been promoted to " .. newfullRank .. ".")
    return true
end

function PLUGIN:Demote(character, demoter)
    if not factionDivisionMap[character:GetFaction()] then return false end
    if not demoter then return false end

    if not self:CanPromoteTarget(demoter, character) then
        demoter:GetPlayer():Notify("You don't have permission to demote this person.")
        return false
    end

    local rankinfo    = character:GetData("rankinfo")
    local newpaygrade = rankinfo.paygrade - 1

    if newpaygrade < 1 then
        demoter:GetPlayer():Notify("This character is already at the lowest rank.")
        return false
    end

    local newrank     = rankTable[rankinfo.division][newpaygrade].rank
    local newfullRank = rankTable[rankinfo.division][newpaygrade].fullRank

    character:SetName(newrank .. " " .. StripRankPrefix(character:GetName()))

    character:SetData("rankinfo", {
        paygrade = newpaygrade,
        division = rankinfo.division,
        fullRank = newfullRank,
        rank     = newrank
    })

    character:GetPlayer():Notify("You have been demoted to " .. newfullRank .. ".")
    return true
end

-- Commands
ix.command.Add("Promote", {
    description = "Promote a character (Admin only).",
    arguments = {
        ix.type.character
    },
    OnRun = function(self, client, target)
        if not factionDivisionMap[target:GetFaction()] then
            return "Only military personnel can be promoted."
        end

        local success = PLUGIN:Promote(target, client:GetCharacter())
        if not success then
            return "Could not promote character."
        end
    end
})

ix.command.Add("Demote", {
    description = "Demote a character (Admin only).",
    arguments = {
        ix.type.character
    },
    OnRun = function(self, client, target)
        if not factionDivisionMap[target:GetFaction()] then
            return "Only military personnel can be demoted."
        end

        local success = PLUGIN:Demote(target, client:GetCharacter())
        if not success then
            return "Could not demote character."
        end
    end
})

ix.command.Add("CharSetRank", {
    description = "Directly set a character's rank (Admin only).",
    adminOnly = true,
    arguments = {
        ix.type.character,
        ix.type.string
    },
    OnRun = function(self, client, target, requestedRank)
        if not IsValid(client) or not target then
            return "Invalid client or target."
        end

        if not factionDivisionMap[target:GetFaction()] then
            return "Only military personnel can have ranks."
        end

        local division = factionDivisionMap[target:GetFaction()]
        if not division then
            return "Character faction does not support ranks."
        end

        local divisionRanks = rankTable[division]
        if not divisionRanks then
            return string.format("Invalid division: %s", tostring(division))
        end

        local foundRank, newPaygrade
        for i, rankData in ipairs(divisionRanks) do
            if string.lower(rankData.fullRank) == string.lower(requestedRank) or
               string.lower(rankData.rank)     == string.lower(requestedRank) then
                foundRank   = rankData
                newPaygrade = i
                break
            end
        end

        if not foundRank then
            return "Invalid rank specified. Please use exact rank name or abbreviation."
        end

        target:SetName(foundRank.rank .. " " .. StripRankPrefix(target:GetName()))

        target:SetData("rankinfo", {
            paygrade = newPaygrade,
            division = division,
            fullRank = foundRank.fullRank,
            rank     = foundRank.rank
        })

        target:GetPlayer():Notify("Your rank has been set to " .. foundRank.fullRank)
        client:Notify("Set " .. target:GetName() .. "'s rank to " .. foundRank.fullRank)

        return "Successfully set rank to " .. foundRank.fullRank
    end
})

if CLIENT then
    function PLUGIN:PopulateCharacterInfo(client, character, tooltip)
        if factionDivisionMap[character:GetFaction()] then
            local rankinfo = character:GetData("rankinfo")
            if rankinfo then
                local rankRow = tooltip:AddRow("rank")
                rankRow:SetText("Rank: " .. rankinfo.fullRank)
                rankRow:SizeToContents()
                rankRow:SetBackgroundColor(Color(0, 97, 117))
            end
        end
    end
end

-- Handle faction changes
function PLUGIN:OnCharacterFactionChanged(client, character, oldFaction, newFaction)
    if factionDivisionMap[oldFaction] and not factionDivisionMap[newFaction] then
        -- Switching to a non-military faction: strip rank
        character:SetName(StripRankPrefix(character:GetName()))
        character:SetData("rankinfo", nil)
    elseif not factionDivisionMap[oldFaction] and factionDivisionMap[newFaction] then
        -- Switching into a military faction: assign starting rank
        self:SetupRank(client, character)
    end
end

-- Network strings
if SERVER then
    util.AddNetworkString("ixRankUpdate")

    function PLUGIN:SyncRankData(character)
        if not character or not factionDivisionMap[character:GetFaction()] then return end

        local client = character:GetPlayer()
        if not IsValid(client) then return end

        local rankinfo = character:GetData("rankinfo")
        if rankinfo then
            net.Start("ixRankUpdate")
                net.WriteEntity(client)
                net.WriteString(rankinfo.fullRank)
                net.WriteString(rankinfo.rank)
            net.Broadcast()
        end
    end
end

if CLIENT then
    net.Receive("ixRankUpdate", function()
        local client    = net.ReadEntity()
        local fullRank  = net.ReadString()
        local rankShort = net.ReadString()

        if IsValid(client) then
            local character = client:GetCharacter()
            if character and factionDivisionMap[character:GetFaction()] then
                -- Update local rank display if needed
            end
        end
    end)
end

-- Permission for managing ranks
ix.permission.Add("canManageRanks", "Permission to manage military ranks")

-- Rank validation helper
function PLUGIN:IsValidRank(division, rankStr)
    if not rankTable[division] then return false end

    for _, rankData in ipairs(rankTable[division]) do
        if rankData.rank == rankStr or rankData.fullRank == rankStr then
            return true
        end
    end

    return false
end

-- Get next rank helper
function PLUGIN:GetNextRank(character)
    if not character or not factionDivisionMap[character:GetFaction()] then return nil end

    local rankinfo = character:GetData("rankinfo")
    if not rankinfo then return nil end

    local nextPaygrade  = rankinfo.paygrade + 1
    local divisionRanks = rankTable[rankinfo.division]

    if divisionRanks and divisionRanks[nextPaygrade] then
        return divisionRanks[nextPaygrade]
    end

    return nil
end

-- Get previous rank helper
function PLUGIN:GetPreviousRank(character)
    if not character or not factionDivisionMap[character:GetFaction()] then return nil end

    local rankinfo = character:GetData("rankinfo")
    if not rankinfo then return nil end

    local prevPaygrade  = rankinfo.paygrade - 1
    local divisionRanks = rankTable[rankinfo.division]

    if divisionRanks and divisionRanks[prevPaygrade] and prevPaygrade > 0 then
        return divisionRanks[prevPaygrade]
    end

    return nil
end